<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<b>{message}</b><br />in <i>{file}</i> on line <i>{line}</i>.<br/>-- {link}' => '<b> {message} </b> <br /> di <i> {file} </i> online <i> {line} </i>. <br/> - {link}',
    'Action' => 'Aksi',
    'Args' => '',
    'Audit' => '',
    'Audit Error in Audit Entry #{entry_id}' => 'Kesalahan Audit dalam Entri Audit # {entry_id}',
    'Audit Module' => 'Modul Audit',
    'BCC' => '',
    'CC' => '',
    'CURL' => '',
    'Called' => 'Dipanggil',
    'Created' => 'Dibuat',
    'Data' => 'Data',
    'Database Trails' => 'Jejak Database',
    'Diff' => 'Perbedaan',
    'Difference' => 'Perbedaan',
    'Download' => 'Unduh',
    'Download eml file' => 'Unduh file eml',
    'Duration' => 'Durasi',
    'Email Messages' => 'Pesan Email',
    'Emailed' => 'Diemail',
    'Entries' => 'Entri',
    'Entry #{id}' => 'Entri # {id}',
    'Entry ID' => 'ID Entri',
    'Error' => 'Kesalahan',
    'Error #{id}' => 'Kesalahan # {id}',
    'Error Code' => 'Kode Kesalahan',
    'Errors' => 'Kesalahan',
    'Extra' => 'Ekstra',
    'Extra Data' => 'Data Ekstra',
    'Field' => 'Bidang',
    'File' => 'File',
    'From' => 'Dari',
    'Guest' => 'Tamu',
    'HTML' => 'HTML',
    'HTML Body' => 'Tubuh HTML',
    'Hash' => '',
    'ID' => '',
    'IP' => '',
    'Javascript' => '',
    'Javascript #{id}' => '',
    'Javascripts' => '',
    'Line' => 'Garis',
    'Mail' => 'Surat',
    'Mail #{id}' => 'Surat # {id}',
    'Mails' => 'Surat',
    'Memory' => 'Memori',
    'Message' => 'Pesan',
    'Model ID' => '',
    'New Value' => 'Nilai Baru',
    'No' => '',
    'Old Value' => 'Nilai Lama',
    'Origin' => 'Asal',
    'Profiling' => 'Profiling',
    'Reply' => 'Balas',
    'Request' => 'Permintaan',
    'Request Method' => 'Metode Permintaan',
    'Stack Trace' => '',
    'Subject' => 'Subjek',
    'Successful' => 'Berhasil',
    'Text' => 'Teks',
    'Text Body' => 'Badan Teks',
    'To' => 'Ke',
    'Trace' => 'Jejak',
    'Trail' => 'Jejak',
    'Trail #{id}' => 'Jejak # {id}',
    'Trails' => 'Jejak',
    'Type' => 'Tipe',
    'User' => 'Pengguna',
    'User ID' => 'ID Pengguna',
    'Yes' => 'Ya',
    'view audit entry' => 'lihat entri audit',
    '{message}' => '',
];
